# Generated by Django 5.2.3 on 2025-06-30 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('progress', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('MTG', 'Meeting'), ('DEV', 'Development'), ('BUG', 'Bug fixing'), ('FIT', 'Fitness'), ('OTH', 'Other')], default='OTH', max_length=10)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
