# Generated by Django 5.2.3 on 2025-07-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reporting_manager',
            field=models.CharField(max_length=20),
        ),
    ]
